name: Kubernetes
on: [push]
jobs:

  build:
    name: Run Kubernetes tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install K3d and run cluster
      run: |
        wget -q -O - https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
        k3d cluster create tempo --api-port 6443 --port "16686:80@loadbalancer"

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'latest' # default is latest stable
      id: install

    - name: Example tests
      run: |
        kubectl cluster-info
        helm install operations/helm/tempo-microservices/ --generate-name
        kubectl create -f example/helm/microservices-extras.yaml
        sleep 120
        kubectl get nodes
        kubectl get deployments
        kubectl get pods
        kubectl get services